/** @type {import('jest').Config} */
module.exports = {
  preset: "jest-expo",
  testEnvironment: "node",
  setupFilesAfterFramework: [],
  setupFilesAfterEnv: ["@testing-library/jest-native/extend-expect"],
  transformIgnorePatterns: [
    "node_modules/(?!(" +
      [
        "expo",
        "expo-router",
        "expo-modules-core",
        "expo-camera",
        "expo-image-picker",
        "expo-image",
        "expo-secure-store",
        "expo-local-authentication",
        "expo-notifications",
        "expo-haptics",
        "expo-updates",
        "expo-clipboard",
        "expo-sharing",
        "expo-screen-capture",
        "expo-build-properties",
        "expo-linking",
        "expo-constants",
        "expo-status-bar",
        "@expo",
        "@expo/vector-icons",
        "@react-native",
        "react-native",
        "react-native-reanimated",
        "react-native-gesture-handler",
        "react-native-screens",
        "react-native-safe-area-context",
        "react-native-svg",
        "@gorhom",
        "@react-native-community",
        "@sentry",
        "lucide-react-native",
      ].join("|") +
    ")/)",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
    "\\.svg$": "<rootDir>/__mocks__/svgMock.js",
  },
  collectCoverageFrom: [
    "app/**/*.{ts,tsx}",
    "api/**/*.{ts,tsx}",
    "store/**/*.{ts,tsx}",
    "hooks/**/*.{ts,tsx}",
    "lib/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "!**/__tests__/**",
    "!**/*.d.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 75,
      statements: 75,
    },
  },
  testPathPattern: "/__tests__/",
  testMatch: [
    "**/__tests__/**/*.{ts,tsx}",
    "**/*.test.{ts,tsx}",
    "**/*.spec.{ts,tsx}",
  ],
};
